wandb_version: 1

elasticity:
  desc: null
  value: 87.01807527572686
noise_level:
  desc: null
  value: 16.4347436809955
num_chains:
  desc: null
  value: 7
num_draws:
  desc: null
  value: 683
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706982331.676403
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.13
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
