wandb_version: 1

elasticity:
  desc: null
  value: 8936.419956235668
noise_level:
  desc: null
  value: 0.9165344566089414
num_chains:
  desc: null
  value: 6
num_draws:
  desc: null
  value: 943
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706989227.530517
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.13
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
